// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDH-BItWvtlFlpP-G7ywZjCbJvdGiH5gkY",
      authDomain: "pro-tech-app-29e61.firebaseapp.com",
      projectId: "pro-tech-app-29e61",
      storageBucket: "pro-tech-app-29e61.appspot.com",
      messagingSenderId: "477376322198",
      appId: "1:477376322198:web:268ae152c2d705a7bb80b7");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyC3jkNrx89FjYJssximwxCLb4POt-uKjiU",
    appId: "1:477376322198:android:d82e4b825b496c02bb80b7",
    messagingSenderId: "477376322198",
    projectId: "pro-tech-app-29e61",
    storageBucket: "pro-tech-app-29e61.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAubN61v-0qiHVFFZ5ZfxPk1epjiPl2v-U",
    appId: "1:1069215963842:ios:89705dd6c6403b6d7af95b",
    messagingSenderId: "1069215963842",
    projectId: "flutterlogin-d7b39",
    storageBucket: "flutterlogin-d7b39.appspot.com",
    iosBundleId: "com.example.googleSignIn",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAubN61v-0qiHVFFZ5ZfxPk1epjiPl2v-U",
    appId: "1:1069215963842:ios:89705dd6c6403b6d7af95b",
    messagingSenderId: "1069215963842",
    projectId: "flutterlogin-d7b39",
    storageBucket: "flutterlogin-d7b39.appspot.com",
    iosBundleId: "com.example.googleSignIn",
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyDH-BItWvtlFlpP-G7ywZjCbJvdGiH5gkY",
      authDomain: "pro-tech-app-29e61.firebaseapp.com",
      projectId: "pro-tech-app-29e61",
      storageBucket: "pro-tech-app-29e61.appspot.com",
      messagingSenderId: "477376322198",
      appId: "1:477376322198:web:268ae152c2d705a7bb80b7");
}
